# Generated by Django 2.0.7 on 2018-07-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicle_ID', models.CharField(max_length=20)),
                ('Make', models.CharField(max_length=40)),
                ('Short_Model', models.CharField(max_length=35)),
                ('Long_Model', models.CharField(max_length=35)),
                ('Trim', models.CharField(max_length=35)),
                ('Derivative', models.CharField(max_length=35)),
                ('Year_introduced', models.CharField(max_length=35)),
                ('Year_discontinued', models.CharField(max_length=35)),
                ('Currentl_Available', models.CharField(max_length=35)),
                ('Images', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'car',
            },
        ),
        migrations.CreateModel(
            name='rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicle_ID', models.CharField(max_length=20)),
                ('used_email', models.CharField(max_length=20)),
                ('start_date', models.CharField(max_length=20)),
                ('end_date', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'rent',
            },
        ),
    ]
