# Generated by Django 2.0.7 on 2018-07-15 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180715_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='used_email',
            new_name='email',
        ),
    ]
