# Generated by Django 2.0.7 on 2018-07-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_car_model_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('website', models.URLField(default='')),
                ('phone', models.IntegerField(default=0)),
                ('sample_image', models.ImageField(blank=True, upload_to='profile_image')),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='model_pic',
            field=models.ImageField(blank='True', upload_to='media'),
        ),
    ]
