# Generated by Django 2.0.7 on 2018-07-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180716_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model_pic',
            field=models.ImageField(default='default.jpeg', upload_to='media'),
        ),
    ]
