# Generated by Django 2.0.7 on 2018-07-18 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180716_2116'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rent',
            new_name='bookvehicle',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='Currentl_Available',
            new_name='Curbookvehiclel_Available',
        ),
        migrations.AlterModelTable(
            name='bookvehicle',
            table='bookvehicle',
        ),
    ]
